apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "naavizl-clickhouse"
spec:
  configuration:
    zookeeper:
      nodes:
        - host: zookeeper.zoo1ns
          port: 2181
    clusters:
      - name: replcluster
        templates:
          podTemplate: clickhouse-with-volume-template
        layout:
          shardsCount: 1
          replicasCount: 1
  templates:
    podTemplates:
      - name: clickhouse-with-volume-template
        spec:
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:22.1
              livenessProbe:
                tcpSocket:
                  port: 8123
                # Number of seconds after the container has started before liveness or readiness probes are initiated
                initialDelaySeconds: 600 
                # How often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1
                periodSeconds: 180
                # Number of seconds after which the probe times out. Defaults to 1 second. Minimum value is 1.
                timeoutSeconds: 60
                # Minimum consecutive successes for the probe to be considered successful after having failed. Defaults to 1. Must be 1 for liveness. Minimum value is 1
                successThreshold: 1
                # When a Pod starts and the probe fails, Kubernetes will try failureThreshold times before giving up
                failureThreshold: 3
              readinessProbe:
                exec:
                  # Try 5 times to access both native and http API entry points.
                  # In case of failure sleep for i*10 sec and retry
                  # This command can take long to to run, so adjust 'timeoutSeconds' accordingly
                    command:
                      - /bin/bash
                      - -c
                      - for i in 1 2 3 4 5; do echo "Attempt $i" && echo -n "version=" && clickhouse-client -q 'select version()' && HTTP=$(wget localhost:8123 -q --tries=1 --timeout=60 -O /dev/stdout) && echo "HTTP=$HTTP" && [ $HTTP == 'Ok.' ] && exit 0; echo "Attempt $i FAILED with above output"; sleep $(($i * 10)); done; exit 1
                initialDelaySeconds: 600
                periodSeconds: 180
                # Number of seconds after which the probe times out. Defaults to 1 second. Minimum value is 1.
                timeoutSeconds: 200
                # When a Pod starts and the probe fails, Kubernetes will try failureThreshold times before giving up
                failureThreshold: 3
              volumeMounts:
                - name: clickhouse-storage-template
                  mountPath: /var/lib/clickhouse
    volumeClaimTemplates:
      - name: clickhouse-storage-template
        spec:
          storageClassName: manual
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
