apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-volume3
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/clickhouse3"
