apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-volume
  namespace: zoo1ns
  labels:
    type: local
spec:
  storageClassName: generic
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/zookeeper"
