apiVersion: apps/v1
kind: Deployment
metadata:
  name: naavizlserver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: naavizlserver
  template:
    metadata:
      labels:
        app: naavizlserver
    spec:
      containers:
      - name: naavizlserver
        image: naavizlserver:v1
---
apiVersion: v1
kind: Service
metadata:
  name: naavizlserver
  namespace: default
spec:
  type: NodePort
  selector:
    app: naavizlserver
  ports:
  - port: 18003
    targetPort: 18003
    nodePort: 30003
    protocol: UDP
    name: udp-18003
  - port: 18004
    targetPort: 18004
    nodePort: 30004
    protocol: TCP
    name: tcp-18004
  - port: 18005
    targetPort: 18005
    nodePort: 30005
    protocol: UDP
    name: udp-18005
  - port: 18006
    targetPort: 18006
    nodePort: 30006
    protocol: TCP
    name: tcp-18006