apiVersion: apps/v1
kind: Deployment
metadata:
  name: naavizlserver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: naavizlserver
  template:
    metadata:
      labels:
        app: naavizlserver
    spec:
      containers:
      - name: naavizlserver
        image: naavizlserver:v1
---
apiVersion: v1
kind: Service
metadata:
  name: naavizlserver
  namespace: default
spec:
  type: NodePort
  selector:
    app: naavizlserver
  ports:
  - port: 18002
    targetPort: 18002
    nodePort: 30002
    protocol: TCP
    name: tcp-18002
  - port: 18003
    targetPort: 18003
    nodePort: 30003
    protocol: UDP
    name: udp-18003