{
 "title": "Clickhouse nFlows",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Total Bytes for Interesting Flows",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "eTime/1000",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    SUM(bytes) as sum_bytes\nFROM $table\n\nWHERE $timeFilter\n\nGROUP BY t\n\nORDER BY t\n",
     "round": "0s",
     "table": "distributed_smflows"
    }
   ]
  },
  {
   "title": "Top 100 Interesting Flows by Bytes",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "eTime/1000",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    flowKey,\n    sTime,\n    eTime,\n    IPv4NumToString(sIP) AS sIP,\n    IPv4NumToString(dIP) AS dIP,\n    sPort,\n    dPort,\n    protocol,\n    application,\n    vlan,\n    obid,\n    packets,\n    rpackets,\n    bytes,\n    rbytes,\n    iflags,\n    riflags,\n    uflags,\n    ruflags\nFROM nflows.smflows\n\nWHERE $timeFilter\n\nORDER BY bytes DESC\n\nLIMIT 100\n",
     "round": "0s",
     "table": "distributed_smflows"
    }
   ]
  },
  {
   "title": "Total Bytes for All Flows",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "eTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    SUM(bytes) as sum_bytes\nFROM $table\n\nWHERE $timeFilter\n\nGROUP BY t\n\nORDER BY t\n",
     "round": "0s",
     "table": "distributed_nflows"
    }
   ]
  },
  {
   "title": "Top 100 Source IPs by Bytes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "eTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    sIP,\n    SUM(bytes)\nFROM $table\n\nWHERE $timeFilter\nGROUP BY sIP\nORDER by SUM(bytes) DESC\nLIMIT 100\n",
     "round": "0s",
     "table": "distributed_nflows"
    }
   ]
  },
  {
   "title": "Top 100 by Destination IPs by Bytes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "eTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    dIP,\n    SUM(bytes)\nFROM $table\n\nWHERE $timeFilter\nGROUP BY dIP\nORDER by SUM(bytes) DESC\nLIMIT 100\n\n",
     "round": "0s",
     "table": "distributed_nflows"
    }
   ]
  },
  {
   "title": "Top 100 Flow Counts by Destination IP",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "eTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    dIP,\n    count()\nFROM $table\n\nWHERE $timeFilter\nGROUP BY dIP\nORDER by count() DESC\nLIMIT 100\n\n",
     "round": "0s",
     "table": "distributed_nflows"
    }
   ]
  },
  {
   "title": "Top 100 Flow Counts by Source IP",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "eTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    sIP,\n    count()\nFROM $table\n\nWHERE $timeFilter\nGROUP BY sIP\nORDER by count() DESC\nLIMIT 100\n\n",
     "round": "0s",
     "table": "distributed_nflows"
    }
   ]
  },
  {
   "title": "Top 100 Flows by Bytes",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "eTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT *\n\nFROM nflows.nflows\n\nWHERE $timeFilter\n\nORDER BY bytes DESC\n\nLIMIT 100\n",
     "round": "0s",
     "table": "distributed_nflows"
    }
   ]
  }
 ]
}